name: Custom Hook

on:
  push:
    paths:
      - 'index2.html'
      - 'employee.xml'

jobs:
  notify-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Call Backend API
        run: |
          curl -X POST http://182.48.194.218:8181/auth/github/actionPayload \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.API_SECRET }}" \
          -d '{
            "event": "file_changed"
          }'
